version: '2'
services:
  gatling:
    image: openjdk:8-jre-alpine
    build: ./gatling
    tty: true
    container_name: gatling
    volumes:
      - /usr/local/bin
    command: /bin/sh

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - gatling
    ports:
      - "80:80"
